{{- if .Values.IPFS.enabled }}
{{- if .Values.ingress.ipfs.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-ipfs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.ipfs.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:    
      paths:
        - backend:
            serviceName: {{ .Release.Name }}-ipfs-service
            servicePort: 5001
          path: /{{ .Release.Name }}/ipfs(/|$)(.*)
{{- end }}
{{- end }}
