apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ipfs-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lotus-node-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5001
      name: ipfs 
