apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-powergate-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lotus-node-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8888
      name: powergate1
    - protocol: TCP
      port: 8889
      name: powergate2
    - protocol: TCP
      port: 6060
      name: powergate3
    - protocol: TCP
      port: 5002
      name: grpc
    - protocol: TCP
      port: 6002
      name: webproxy
