{{- if .Values.persistence.snapshots.enabled }}
{{- if (not (lookup "snapshot.storage.k8s.io/v1beta1" "VolumeSnapshotClass" "" "csi-aws-vsc")) }}
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
{{- end }}

{{- if and (not (lookup "storage.k8s.io/v1" "StorageClass" "" "ebs-sc")) (eq "-" .Values.persistence.lotus.storageClassName) (eq "-" .Values.persistence.ipfs.storageClassName) (eq "-" .Values.persistence.powergate.storageClassName) }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- end }}
